concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_LoadTests_Python_ParDo_Dataflow_Batch:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Python ParDo Dataflow Batch''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: default
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_ParDo_Dataflow_Batch_10_Iterations.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_ParDo_Dataflow_Batch_200_Iterations.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_ParDo_Dataflow_Batch_10_Counters.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_ParDo_Dataflow_Batch_100_Counters.txt

          '
        test-language: python
        test-type: load
    - continue-on-error: true
      id: datetime
      name: Set current datetime
      run: 'echo "datetime=$(date ''+%m%d%H%M%S'' --utc)" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: run ParDo Dataflow Batch Python Load Test 1 (10 iterations)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.pardo_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_ParDo_Dataflow_Batch_test_arguments_1
          }} --job_name=load-tests-python-dataflow-batch-pardo-1-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run ParDo Dataflow Batch Python Load Test 2 (200 iterations)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.pardo_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_ParDo_Dataflow_Batch_test_arguments_2
          }} --job_name=load-tests-python-dataflow-batch-pardo-2-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run ParDo Dataflow Batch Python Load Test 3 (10 counters)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.pardo_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_ParDo_Dataflow_Batch_test_arguments_3
          }} --job_name=load-tests-python-dataflow-batch-pardo-3-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run ParDo Dataflow Batch Python Load Test 4 (100 counters)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.pardo_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_ParDo_Dataflow_Batch_test_arguments_4
          }} --job_name=load-tests-python-dataflow-batch-pardo-4-${{ steps.datetime.outputs.datetime
          }}'''
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Python_ParDo_Dataflow_Batch
        job_phrase:
        - Run Load Tests Python ParDo Dataflow Batch
    timeout-minutes: 200
name: LoadTests Python ParDo Dataflow Batch
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Python_ParDo_Dataflow_Batch.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
